### ISSUE TITLE
Copyright addition is not consistent with the original copyright

### ISSUE THREAD

**Issue by nkruglikov** [Facenapalm/Highlight.js#1]
Hi,
I noticed a copyright at the bottom of the page. It looks nice and funny, but I think that it must be in name-surname order, like the original signature.
![7](https://cloud.githubusercontent.com/assets/8327627/13554254/3ae57c48-e3b4-11e5-9e35-3429f170a55e.png)

**Comment by Facenapalm** [comment]
Done. :)
