### ISSUE TITLE
Типографика

### ISSUE THREAD

**Issue by bryzgaloff** [Facenapalm/Highlight.js#3]
Предлагаю следующие типографические правила:
1. В качестве тире использовать именно длинное тире: —
2. В качестве кавычек использовать «французские ёлочки»

Сейчас актуально изменить описание скрипта Вани (@YaLTeR)

**Comment by Facenapalm** [comment]
Тире я и так использую длинное. Вроде. Насчёт кавычек не уверен, холиварный случай. Но я не против.
Тут есть ещё один вопрос для обсуждения: нужно ли нам в readme оформлять описания ненумерованным списком изменений, как в свежедобавленном скрипте. С одной стороны, воспринимается лучше, с другой стороны - у нас же весь readme будет из списков состоять.

**Comment by YaLTeR** [comment]
Про кавычки и тире я не против. Список сделал, потому что показалось более читаемо, чем без списка. ¯\_(ツ)_/¯

**Comment by Facenapalm** [comment]
Ну просто тогда и Highlight.js надо бы переделать в список.

**Comment by bryzgaloff** [comment]
В целом списком делать логичнее, но, черт, и правда: списки-списки-списки будут. Давайте лучше придерживаться стиля без списка, оформляя в связный текст, иначе слишком отрывисто получится.
