### ISSUE TITLE
Именования скриптов

### ISSUE THREAD

**Issue by bryzgaloff** [Facenapalm/Highlight.js#5]
Предлагаю все скрипты переименовать по аналогии с SubmissionsMod, то есть указывать, какой элемент меняется и дбавлять "Mod". Например, StandingsMod и ProblemListMod. @YaLTeR, @Facenapalm, что скажете? Свои наработки планирую переименовать в ближайших коммитах.

**Comment by bryzgaloff** [comment]
Хотя... Так ведь обновления сломаются... Тогда предлагаю принять это правило именования для будущих скриптов.

**Comment by Facenapalm** [comment]
С учётом того, что у нас с самого начала не было никаких общих правил, предлагаю всё ещё оставлять это на усмотрение автора скрипта.
А предложенный способ хренов тем, что одну и ту же страницу могут менять разные скрипты.

**Comment by Facenapalm** [comment]
Раз мы ни к чему не пришли, оставим всё как есть и закроем обсуждение, пожалуй.
